# Generated by Django 4.1.3 on 2022-11-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Города', 'verbose_name_plural': 'Поселки'},
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя города'),
        ),
    ]
